'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18408
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("La_Andaluza_Almacen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property accessories_dictionary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_dictionary", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_exit_3_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_exit_3_256", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_exit_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_exit_4", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_xit_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_xit_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property applications_system_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_system_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appointmentmissed16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appointmentmissed16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_down_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_up_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_add", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_delete", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkbox_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbox_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_apply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_apply", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_cancel_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_cancel_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_ok_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_ok_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_print_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_print_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_save_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_save_5", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_save_5_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_save_5_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_save_5_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_save_5_32", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_add_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_add_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_clear_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_clear_21", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_clear_locationbar_ltr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_clear_locationbar_ltr", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_group", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_remove_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_remove_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_documents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_documents", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_important_2_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_important_2_256", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_important_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_important_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_mail", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_mail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_mail_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_new_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_new_256", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_notice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_notice", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_notice_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_notice_256", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_package", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_package_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_package_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_special() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_special", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property family() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("family", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_magnify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_magnify", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imprimir_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imprimir_16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LAconTexto48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LAconTexto48x48", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LaIconPng1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaIconPng1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LAsinTexto48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LAsinTexto48x48", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LASoloTexto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LASoloTexto", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoBAndalsoejaLa1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoBAndalsoejaLa1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoBAndalsoejaLa2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoBAndalsoejaLa2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property LogoBAndalsoejaLa21() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoBAndalsoejaLa21", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoJR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoJR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoLA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoLA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_forward_4_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_forward_4_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_forward_4_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_forward_4_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_send_3_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_send_3_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Modificar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modificar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property network_transmit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network_transmit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_broken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_broken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_broken2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_broken2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_halfgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_halfgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package_installed_updated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_installed_updated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_excel_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_excel_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_white_word_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_white_word_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanner_barcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner_barcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property scanner_barcode1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner_barcode1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sp2b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp2b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property system_help_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("system_help_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_suit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_suit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vcard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vcard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_refresh_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_refresh_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_refresh_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_refresh_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property window_duplicate1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("window_duplicate1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property window_new() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("window_new", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property window_new_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("window_new_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
